services:
  postgres:
    image: postgres:16.1
    container_name: postgrescontainer
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgresvolume:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.dl/schema.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmincontainer
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DEFAULT_ADD_SERVER_DB: 6000
      PGADMIN_LISTEN_PORT: 6000
    expose:
      - "6000"
    ports:
      - "9192:6000"
    volumes:
      - pgadminvolume:/var/lib/pgadmin


volumes:
    postgresvolume:
    pgadminvolume: